### Do Pine problem 4.1 and 4.3 


4.1)Write a Python program that calculates how much money you can spend each day for lunch for the rest of the month based on today’s date and how much money you currently have in your lunch account. The program should ask you: (1) how much money you have in your account, (2) what today’s date is, and (3) how many days there are in month. The program should return your daily allowance. The results of running your program should look like this:

In [6]:
account_total = 118.39 #$
dom = 17 #day of month
dim = 30 #total days in month
tdspend = account_total/(dim-dom+1) #daily budget for lunch

print('Money in your lunch account? $',str(account_total))
print('What day of the month is today?', str(dom))
print('How many days in this month?', str(dim))
print("You can spend = ${0:0.2f} each day for the rest of the month".format(tdspend))

Money in your lunch account? $ 118.39
What day of the month is today? 17
How many days in this month? 30
You can spend = $8.46 each day for the rest of the month


4.3) Create the following data file and then write a Python script to read it into a three NumPy arrays with the variable names f, a, da for the frequency, amplitude, and amplitude error.

In [17]:
f, a, da = np.loadtxt("chap4_problem_4.3.txt", skiprows=3,  unpack=True )

In [21]:
f




array([  0.75  ,   1.7885,   2.8269,   3.8654,   4.9038,   5.9423,
         6.9808,   8.0192,   9.0577,  10.0962,  11.1346,  12.1731,
        13.2115,  14.25  ])

In [22]:
a

array([ 13.52,  12.11,  14.27,  16.6 ,  22.91,  35.28,  60.99,  33.38,
        17.78,  10.99,   7.47,   6.72,   4.4 ,   4.07])

In [23]:
da

array([ 0.32,  0.92,  0.73,  2.06,  1.75,  0.91,  0.99,  0.36,  2.32,
        0.21,  0.48,  0.51,  0.58,  0.63])